Added dockerfile to allow deploying via docker
PretendoNetwork/BOSS pull request #1
Opened 2021-08-31 05:15 UTC by AnnoyingRain5

2021-08-31 10:37 UTC, mrjvs requested changes
Hey, thanks for the PR.

There are a few things needed before this can be approved:
 1. Proper configuration, best practice for dockerfiles is to have configuration be set through environment if possible. in this case it needs some extra code but it is possible. So every config key needs to be able to be setup through environment variables
 2. Static image version, always using current is not recommended as it may break just by inactiveness. so dont use ` current` in the image.
 3. proper image layers:
     - Do dependencies before copying source, this will make sure dependencies are only downloaded when needed.
     - No unnecesary steps, we don't need an entrypoint, just do a `CMD node .`
     - Do workdir at the top below FROM
 4. Comment the dockerfile, we need to know whats going on :P
 5. Add a .dockerignore file, right now it will add the config.json and entire node_modules to the context when building

Also check review comments

2021-08-31 10:37 UTC, mrjvs commented on dockerfile
> +WORKDIR /app
duplicate workdir

2021-08-31 10:37 UTC, mrjvs commented on dockerfile
> +ENTRYPOINT "/app/startup.sh"
No endline at file

2021-08-31 10:37 UTC, mrjvs commented on dockerfile
> +EXPOSE 8080/tcp
after adding environment variable support for config, make sure the app always run on 8080 using the env

2021-09-03 13:32 UTC, mrjvs approved these changes

2021-09-03 13:32 UTC, mrjvs commented
@jonbarrow tested dockerfile, works and looks good. ready for merge

2024-07-22 17:17 UTC, MatthewL246 commented
Closing because this server has now been Dockerized in #9.

2024-07-22 17:17 UTC, closed without merging